baseURL = 'http://hobbyfarm.github.io/'
languageCode = 'en-us'
title = 'HobbyFarm Documentation'
offlineSearch = true
enableEmoji = true
[module]
proxy = 'direct'
[[module.imports]]
path = 'github.com/google/docsy'
[[module.imports]]
path = 'github.com/google/docsy/dependencies'
