baseURL = 'http://hobbyfarm.github.io/'
languageCode = 'en-us'
title = 'HobbyFarm'
offlineSearch = true
enableEmoji = true
[module]
proxy = 'direct'
[[module.imports]]
path = 'github.com/google/docsy'
[[module.imports]]
path = 'github.com/google/docsy/dependencies'
[menu]
[[menu.main]]
  name = 'Home'
  weight = 1
  pageRef = '/'
[[menu.main]]
  name = 'Github'
  weight = 99
  url = 'https://github.com/hobbyfarm/hobbyfarm'